---
- name: Download pip
  shell: curl -O https://bootstrap.pypa.io/get-pip.py

- name: Install pip
  shell: sudo python get-pip.py

- name: Install AWS CLI
  pip: name=awscli

- name: Copy from S3
  shell: AWS_ACCESS_KEY_ID={{lookup('env','AWS_ACCESS_KEY_ID')}} AWS_SECRET_ACCESS_KEY={{lookup('env', 'AWS_SECRET_ACCESS_KEY')}} aws s3 cp s3://{{lookup('env', 'S3_BUCKET')}}/{{lookup('env', 'S3_KEY')}} /var/packages/rpm/el7/unstable/

- name: Re-index RPM repository
  shell: createrepo /var/packages/rpm/el7/unstable/x86_64

