---
- name: print os version
  shell: cat /etc/issue

- name: update yum
  shell: sudo yum update

- name: install docker
  shell: curl -sSL https://get.docker.com/ | sh

- name: start docker service
  service: name=docker state=started

- name: pull latest rippled-build-bot container
  shell: sudo docker pull stevenzeiler/rippled-build-bot

- name: run rippled-build-bot container
  shell: sudo docker run -d stevenzeiler/rippled-build-bot

