---
- name: Check if docker is installed
  command: which docker
  register: docker_installed

- name: update yum
  shell: sudo yum update
  when: not docker_installed

- name: install docker
  shell: curl -sSL https://get.docker.com/ | sh
  when: not docker_installed

- name: start docker service
  service: name=docker state=started

- name: pull latest rippled-build-bot container
  shell: sudo docker pull stevenzeiler/rippled-build-bot

- name: run rippled-build-bot container
  shell: sudo docker run -d stevenzeiler/rippled-build-bot

