---
- name: Check if docker is installed
  command: which docker
  register: docker_installed

- name: update yum
  shell: sudo yum update
  when: not docker_installed

- name: install docker
  shell: curl -sSL https://get.docker.com/ | sh
  when: not docker_installed

- name: start docker service
  service: name=docker state=started

- name: create GPG key directory
  file: path=/etc/gpg state=directory

- name: install GPG private.key 
  copy: content="{{private_key}}" dest=/etc/gpg/private.key

- name: pull latest rippled-package-builder:latest container
  shell: sudo docker pull stevenzeiler/rippled-package-builder:latest

- name: run rippled-package-builder:latest container
  shell: sudo docker run -d -v -p 5000:5000 /var/run/docker.sock:/var/run/docker.sock -v /etc/gpg/private.key:/usr/src/app/rpm-builder/private.key -e "AWS_ACCESS_KEY_ID={{aws_access_key_id}}" -e "AWS_SECRET_ACCESS_KEY={{aws_secret_access_key}}" -e "GPG_PASSPHRASE={{gpg_passphrase}}" -e "S3_BUCKET_STABLE={{s3_bucket_stable}}" -e "S3_BUCKET_UNSTABLE={{s3_bucket_unstable}}" -e "S3_BUCKET_NIGHTLY={{s3_bucket_nightly}}" -e "SQS_REGION={{sqs_region}}" -e "SQS_QUEUE_UPLOADED={{sqs_queue_uploaded}} -e "SQS_QUEUE_DEPLOYED={{sqs_queue_deployed}}" -e "SQS_QUEUE_TESTED={{sqs_queue_tested}}" -e "SQS_QUEUE_FAILED={{sqs_queue_failed}}" -e "SLACK_TOKEN={{slack_token}}" stevenzeiler/rippled-package-builder:latest
